all:
	pdflatex CMPE216_template.tex && bibtex CMPE216_template.aux
clean:
	rm CMPE216_template.aux CMPE216_template.log CMPE216_template.spl CMPE216_template.bbl CMPE216_template.blg CMPE216_template.pdf